services:
  - type: web
    name: scraper
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: HEADED
        value: "true"
      - key: DISPLAY
        value: ":99"
      - key: PORT
        value: "3000"

